version: '3.3'

networks:
  pool-net:
    driver: bridge

volumes:
    monerod: {}
    wallet: {}
    redis: {}
    pool: {}
    certs: {}
    certs-data: {}

services:

  #prometheus:
  #  image: prom/prometheus
  #  container_name: prometheus
  #  volumes:
  #    - ./prometheus/:/etc/prometheus/
  #    - prometheus_data:/prometheus
  #  command:
  #    - '-config.file=/etc/prometheus/prometheus.yml'
  #    - '-storage.local.path=/prometheus'
  #    - '-alertmanager.url=http://alertmanager:9093'
  #    - '-storage.local.memory-chunks=100000'
  #  restart: unless-stopped
  #  expose:
  #    - 9090
  #  #ports:
  #    #- 9090:9090
  #  networks:
  #    - monitor-net
  #  labels:
  #    org.label-schema.group: "monitoring"

  #nginx:
  #  build: ./nginx
  #  container_name: nginx
  #  restart: unless-stopped
  #  networks:
  #    - pool-net
  #  volumes:
  #    - certs:/etc/letsencrypt
  #    - certs-data:/data/letsencrypt
  #    - ./nginx/conf/:/etc/nginx
  #  ports:
  #    - 80:80
  #    - 443:443

  monerod:
    build: ./monerod
    container_name: monerod
    image: local/monerod:0.10.3.1
    restart: unless-stopped
    #stdin_open: true
    tty: true
    environment:
      - LOG_LEVEL=1
      - P2P_BIND_IP=0.0.0.0
      - P2P_BIND_PORT=18080
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=18081
      - TESTNET=false
      - BLKCHAIN_BOOTSTRAP=true
      - BLKCHAIN_VERIFY=0
    networks:
      - pool-net
    volumes:
      - monerod:/root/.bitmonero
      - wallet:/wallet
    expose:
      - 18080
      - 18081
    ports:
      - 18080:18080
      - 127.0.0.1:18081:18081

  monero_wallet:
    build: ./monero_wallet
    container_name: monero_wallet
    image: local/monero_wallet:0.10.3.1
    restart: unless-stopped
    tty: true
    env_file:
      - monero_wallet.env
    environment:
      - RPC_BIND_IP=0.0.0.0
      - RPC_BIND_PORT=18082
    networks:
      - pool-net
    volumes:
      - wallet:/wallet
    expose:
      - 18082
    ports:
      - 127.0.0.1:18082:18082

  redis:
    build: ./redis
    container_name: redis
    image: local/redis:mainnet
    restart: unless-stopped
    volumes:
      - redis:/redis
      - ./configs/redis.conf:/tmp/redis.conf
    networks:
      - pool-net
    expose:
      - 6379
    command:
      - redis-server
      - /tmp/redis.conf

  # MAKE Sure to update ADDRESS and API PASSWORD in Config.json
  pool:
    build: ./cryptonote-universal-pool
    container_name: pool
    image: local/cryptonote-universal-pool:latest
    restart: unless-stopped
    volumes:
      - pool:/pool
      - ./configs/pool/config.json:/cryptonote-universal-pool/config.json
      - ./configs/pool/config-web.js:/cryptonote-universal-pool/website/config.js
      - ./configs/pool/home.html:/cryptonote-universal-pool/website/pages/home.html
      - ./configs/pool/index.html:/cryptonote-universal-pool/website/index.html
    networks:
      - pool-net
    expose:
      - 8117
      - 3333
      - 5555
      - 7777
      - 8888
    ports:
      - 3333:3333
      - 5555:5555
      - 7777:7777
      - 8888:8888

  # Update htpasswd (if needed) and hostname in nginx conf sites-enabled
  nginx:
    build: ./nginx
    container_name: nginx
    image: local/nginx:latest
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - ./configs/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443


